// ou are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"


var findTheDifference = function(s, t) {
    var array1=s.split("");
    var array2=t.split("");
    loop1:
    for(i=0;i<array1.length;i++){
    loop2:
    for(j=0;j<array2.length;j++){
          if(array1[i]==array2[j]){
              
              array1.splice(i,1);
              array2.splice(j,1);
                i--;
              break loop2;
            
              
          }
    
        }
       
      }
  return array2.join("")


  
};